services:
  orch:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env.docker
    environment:
      - APPLICATION_PORT=3000
    ports:
      - "${ORCH_PORT:-3004}:${APPLICATION_PORT:-3000}"
